### ISSUE TITLE
Europe

### ISSUE THREAD

**Issue by philipus** [neuroinfo-os/BSTIM-Covid19#16]
Do you think of extending the analysis on the spread in Europe. Also, I guess that the development of the pandemic especially at the boarders of Germany (i.e. Germany-France) can also depend on the the situation in the other countries.

How much computer resources were needed to do this analysis?

**Comment by pnieters** [comment]
Morning,
extending to a wider European area would require data on a similar resolutions as counties and cities in Germany per day. After integrating data from different countries, a simple model without interaction kernel should already be ready to run.
To run with an interaction kernel, one would also implement a spatial/temporal sampling that adheres to the geometry of municipality / county / city ... for which reports are gathered.
Running one model for the entire time-series is quite computationally expansive and would take ~ 3-4 hours on about 100 CPU cores for the interactions + likely more than 24h to sample the parameters of the model. Because we've decided to run models once per day, and then take into account 21 days of data, the current runtime is a couple of hours on an HPC machine at JSC in FZ Juelich. 100 cores for sampling time and coordinate, one node (2x64 cores) for sampling the posterior.
Optimizations and possible GPU acceleration are being evaluated ;)

We're trying to keep issues code-specific, so I'm closing the issue -- hopefully some of the information was interesting nonetheless!

**Comment by philipus** [comment]
Moin

Thank you for your detailed answer even though the question was not code relevant.

100 CPUs wow...

Do you think an approach from neural network area stnn ("Spatio-Temporal Neural Networks for Space-Time Series Forecasting and Relation Discovery") could be applied with equally performance in prediction performances?!

Best and thank you once more. It least I understood that this approach can not applied on my notebook 👍
